
import = [
	"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
startup_mode = "Fullscreen"

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"
args = [
	"-l",
	"-c",
	"tmux attach || tmux",
]
